name: build
on:
  push: ~
  pull_request: ~
jobs:
  ci:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]

    steps:
      - name: Setup python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Checkout
        uses: actions/checkout@v2

      - name: Git User config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0

      - name: Install dependencies
        run: poetry install

      - name: Pylint
        run: poetry run pylint docker_devbox_installer stepbystep

      - name: Pytest with coverage
        if: matrix.os == 'ubuntu-latest'
        run: poetry run coverage run --source=docker_devbox_installer,stepbystep -m pytest

      - name: Pytest without coverage
        if: matrix.os != 'ubuntu-latest'
        run: poetry run pytest

      - name: Coveralls
        if: matrix.os == 'ubuntu-latest'
        run: poetry run coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]

    steps:
      - name: Setup python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Checkout
        uses: actions/checkout@v2

      - name: Git User config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0

      - name: Install dependencies
        run: poetry install

      - name: Poetry build
        run: poetry build

      - name: Pyinstaller build
        run: poetry run pyinstaller --clean -y --dist ./dist docker-devbox-installer.spec

      - uses: actions/upload-artifact@v2
        with:
          name: dist-${{ matrix.os }}
          path: dist/

  commitlint:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2

  release:
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    needs: [ci, commitlint, build]

    runs-on: ubuntu-latest

    steps:
      - name: Setup python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Git User config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"

      - uses: actions/download-artifact@v2
        with:
          name: dist-ubuntu-latest
          path: build/ubuntu-latest

      - uses: actions/download-artifact@v2
        with:
          name: dist-windows-latest
          path: build/windows-latest

      - uses: actions/download-artifact@v2
        with:
          name: dist-macos-latest
          path: build/macos-latest

      - name: Install python-semantic-release
        run: pip install git+https://github.com/Toilal/python-semantic-release@master

      - name: Move binaries to dist directory
        run: |
          ls -R build/
          mkdir -p dist/
          mv build/macos-latest/docker-devbox-installer ./dist/docker-devbox-installer-$(semantic-release print-version)-macos
          mv build/ubuntu-latest/docker-devbox-installer ./dist/docker-devbox-installer-$(semantic-release print-version)-linux
          mv build/windows-latest/docker-devbox-installer.exe ./dist/docker-devbox-installer-$(semantic-release print-version)-windows.exe

      - name: Publish release
        run: semantic-release -v DEBUG publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge main to develop
        uses: robotology/gh-action-nightly-merge@v1.3.2
        with:
          stable_branch: 'main'
          development_branch: 'develop'
          allow_ff: true
          user_name: github-actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
